name: Build and Publish Docker image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  push_to_registry:
    if: github.ref == 'refs/heads/master'
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # images: ghcr.io/nhanus/otrecorder
          images: docker.pkg.github.com/nhanus/owntracks-docker-recorder-rpi/otrecorder          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}        
      - name: Build only docker images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          load: true
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Push docker image
        run: docker push docker.pkg.github.com/nhanus/owntracks-docker-recorder-rpi/otrecorder:${{ steps.docker_meta.outputs.version }}
      - name: Push docker image
        run: docker push docker.pkg.github.com/nhanus/owntracks-docker-recorder-rpi/otrecorder:latest